name = "ProximalBundleMethod"
uuid = "0a5fdb40-eec4-43de-b7bc-675295652e2c"
authors = ["Mateo Diaz <mateodd@icloud.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
