* Proximal Bundle Method

This repository is a supplement for "Optimal Convergence Rates for the Proximal Bundle Method".

** One-time setup

*The instructions assume that your current working directory is the base of this repository.*

The repository is completely written in Julia. To set the environment install Julia 1.6.1 from https://julialang.org/downloads/ and make sure =julia= is available in your =PATH=. The SVM example computes the true minimum value using [[https://www.gurobi.com/downloads/gurobi-optimizer-eula/][Gurobi]]. To run it you will need to install Gurobi and have an active license.

Instantiate the Julia packages
#+begin_src bash
$ julia --project=. -e "import Pkg; Pkg.instantiate()"
#+end_src

Besides Julia, you need to download the data used for the experiments. For this run.

#+begin_src bash
$ ./scripts/download_data.sh
#+end_src


** Running

*** Regression example

Run
#+begin_src bash
$ julia --project=scripts scripts/run_regression_experiment.jl
#+end_src

This saves the results in the folder =results/regression=.

*** Support vector machine example

Run
#+begin_src bash
$ julia --project=scripts scripts/run_svm_experiment.jl
#+end_src

The script saves the results in the folder =results/svm=.


** Note

The file structure and README of this repository were inspired by those of [[https://github.com/google-research/FirstOrderLp.jl][FirstOrderLp]].
